
pipelines:
  custom:
    release:
      - step:
          image: node:16
          script:
            - npm version minor
            - git push -f
            - docker login -u $DOCKER_USER -p $DOCKER_PASS
            - docker build . -f Dockerfile.prod -t jamesdalboth/dalble:$(node -p "require('./package.json').version") -t jamesdalboth/dalble:latest
            - docker push jamesdalboth/dalble -a
          services:
            - docker
      - step:
          image: hashicorp/terraform:1.3.7
          script:
            - /bin/sh ./scripts/apply.sh --approve --version $(git describe --tags $(git rev-list --tags --max-count=1) | cut -c2-)