
pipelines:
  branches:
    main:
      - step:
          image: node:16
          script:
            - npm version minor
            - git push --tags
            - docker login -u $DOCKER_USER -p $DOCKER_PASS
            - docker build . -f Dockerfile.prod -t jamesdalboth/dalble:$(node -p "require('./package.json').version") jamesdalboth/dalble:latest
            - docker push jamesdalboth/dalble -a
          services:
            - docker
      - step:
          image: hashicorp/terraform:1.3.7
          script:
            - /bin/sh ./scripts/apply.sh --approve