
pipelines:
  custom:
    release:
      - step:
          image: node:16
          script:
            - npm version minor
            - VERSION="$(node -p "require('./package.json').version")"
            - git push -f
            - docker login -u $DOCKER_USER -p $DOCKER_PASS
            - docker build . -f Dockerfile.prod -t jamesdalboth/dalble:$VERSION -t jamesdalboth/dalble:latest
            - docker push jamesdalboth/dalble -a
            - echo "export VERSION=$VERSION" >> set_env.sh
          services:
            - docker
          artifacts: # define the artifacts to be passed to each future step
            - set_env.sh
      - step:
          image: hashicorp/terraform:1.3.7
          script:
            - source set_env.sh
            - apk add bash
            - /bin/bash ./scripts/apply.sh --version $VERSION --approve=true