name: Terraform CI

on:
  - pull_request

jobs:
  initialize:
    name: Initialize
    runs-on: ubuntu-latest
    steps:
      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [initialize]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Terraform Fmt
        run: terraform fmt -recursive -diff=true -check=true .
      - name: Terraform Validate
        run: terraform validate
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: modules
          quiet: true
          soft_fail: false
          framework: terraform
          output_format: junitxml
          output_file_path: reports
          download_external_modules: true
          log_level: WARNING
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          path: 'results_junitxml.xml'
          name: 'Checkov'
          reporter: java-junit
          working-directory: 'reports'
          fail-on-error: false
